[build]
  command = "npm run build"
  functions = "built-lambda"
  publish = "build"

[template.environment]
  GITHUB_CLIENT_ID = "90d7f294e019428050e6"
  GITHUB_CLIENT_SECRET = "64a021702f50bc616d01474309bf72bac0128270" 
  GITHUB_APP_ID = "1075066"
